### ISSUE TITLE
Cannot find reference 'Main' in '__init__.py'

### ISSUE THREAD

**Issue by wangzilinn** [markNZed/ARTimeNAB.jl#3]
Hi @markNZed

When I tried to merge ARtime into the NAB library I found that it would not work and produced some error messages》
The output from the IDE is:
![image](https://user-images.githubusercontent.com/18616796/174464425-00ce152a-aee8-4211-958e-855eb8909e21.png)
The error in the code is reported as:
![image](https://user-images.githubusercontent.com/18616796/174464437-3abc01e7-5c6c-4433-81f4-862912b24a97.png)
Does the above error report have anything to do with the python version? Or am I missing something
After I added some printing to the above code, the output of the IDE was:
![image](https://user-images.githubusercontent.com/18616796/174464518-fab0f95d-177f-4e51-96fd-c2b1948bfa41.png)

**Comment by markNZed** [comment]
Hi, you should not need to merge ARTimeNAB yourself, instead use https://github.com/numenta/NAB See https://github.com/numenta/NAB/blob/master/nab/detectors/ARTime/README.md for details on how to setup the ARTime detector inside NAB.
