### ISSUE TITLE
Non NAB Version

### ISSUE THREAD

**Issue by Mrforeman1** [markNZed/ARTimeNAB.jl#4]
Hello is there a version of ARTime that can be used outside of NAB.  I am looking for online structural break detection algorithm and not necessarily use NAB

Thanks

**Comment by markNZed** [comment]
This version of ARTime does not depend on NAB. The dependency is in the other direction, NAB depends on this version of ARTime (for the ARTtime detector in NAB).

**Comment by Mrforeman1** [comment]
Thanks.  I've have been using a form of SVDD to determine a structural break in the time series after training on the first 100 or so bars.  Does the ARTime train off of a predetermined length or is it completely hands off?

**Comment by markNZed** [comment]
It is an online learning algorithm with a parameter for the length of an initial anomaly free training period. It is probably not well suited to what you want because after detecting an anomaly it learns to ignore similar patterns in the future.
