### ISSUE TITLE
Can I understand your method as an online learning method which update the model step-by-step over time?

### ISSUE THREAD

**Issue by GodofRap** [markNZed/ARTimeNAB.jl#5]
I'm really impressed by this method and am going to use it as a compared method in my experiment. 

Can I interpret it as an advanced version of the Hierarchical Temporal Memory method? Also, is this method an unsupervised and online learning method?

**Comment by markNZed** [comment]
It is based on ART, not HTM, and in this implementation it is unsupervised and using online learning.
