### ISSUE TITLE
Allocation problem stops running.

### ISSUE THREAD

**Issue by GodofRap** [markNZed/ARTimeNAB.jl#7]
Hi, I really like your method and want to use it as a compared method. Currently, I'm running the ARTime under NAB. I think I have set everything correctly and tried to run the following command:

python run.py -d ARTime --detect --optimize --score --normalize --windowsFile labels/combined_windows_new.json

However, I encounter the following error, which I have spent a lot of time on it and don't know how to fix it. Hope you can provide some guidance. 

Running detection step
0: Beginning detection with ARTime for realAWSCloudwatch/ec2_cpu_utilization_77c1ca.csv
2: Beginning detection with ARTime for realAWSCloudwatch/ec2_network_in_5abac7.csv
1: Beginning detection with ARTime for realAWSCloudwatch/ec2_disk_write_bytes_1ef3de.csv

signal (11): Segmentation fault
in expression starting at none:0
Allocations: 2494562 (Pool: 2493386; Big: 1176); GC: 2
Segmentation fault (core dumped)

**Comment by markNZed** [comment]
I guess one solution would be to have a Dockerfile that works. Are you familiar with Docker?

**Comment by GodofRap** [comment]
Oh. I missed your response. I didn't receive a notification on my own page. I still need your help and this issue blocks me for quite a while. I know some basic things about docker containers.

**Comment by markNZed** [comment]
I've updated the README with a link to a docker environment https://github.com/markNZed/ARTimeNAB.jl#running-artime-with-nab If that works, or does not work, please let me know here.

**Comment by GodofRap** [comment]
Really appreciate your help. It is working now! As I don't have much experience with Docker, I'm wondering how I can use IDE (e.g., PyCharm) to link and develop upon this project, so that I can set a stop point for developing and debugging as a usual python project.

**Comment by markNZed** [comment]
Thanks for letting me know the docker works for you. I'm sorry but I don't have time to support you in developing with docker. I was using VScode when I was working on this project. On another project that I'm working on now I'm using VScode to debug on remote docker containers, there is a lot of info on the web about setting that up. ARTime is written in Julia not Python.
